name: publish package
# Manually trigger
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    # Add permissions for GITHUB_TOKEN
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          lein: 'latest'
      - name: Configure GPG Key
        run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GH_PACKAGES_GPG_SIGNING_KEY }}
      - name: Publish package
        run: lein deploy github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
